DROP TABLE IF EXISTS cliente;
CREATE TABLE cliente (
  id int(11) NOT NULL AUTO_INCREMENT,
  nombre varchar(128) DEFAULT NULL,
  apellido varchar(128) DEFAULT NULL,
  direccion varchar(128) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;

ALTER TABLE cliente
ADD CONSTRAINT FK_Detalle FOREIGN KEY (id) REFERENCES detalle_cliente(id)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE cliente DROP CONSTRAINT FK_Detalle;